### ISSUE TITLE
Eval bug: Build succeeds with warnings but fails to load models

### ISSUE THREAD

**Issue by Kotali-2019** [iacopPBK/llama.cpp-gfx906#9]
### Name and Version

# ./llama-cli --version
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon Pro VII, gfx906:sramecc+:xnack- (0x906), VMM: no, Wave Size: 64
version: 7216 (4cf0b39b)
built with cc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0 for x86_64-linux-gnu

### Operating systems

Linux

### GGML backends

HIP

### Hardware

Two sockets xeon E5-2696 V3 + MI50 16GB

### Models

gpt-oss 20b mxfp4 gguf

### Problem description & steps to reproduce

Hi, I’m not sure if I injected the correct TensileLibrary, so I tried installing and removing ROCm from versions 6.4.4 to 7.1.0 for testing. I also tested using the prebuilt Docker image from https://github.com/mixa3607/ML-gfx906. All results led to the same outcome: the mainstream fork works fine, but this fork shows warnings during the build and crashes when loading any model.
Here are the commands I used to build the bin folder (I also tried your compiled script and encountered the same errors):
**cmake -S . -B build  -DGGML_HIP=ON -DAMDGPU_TARGETS=gfx906 -DGGML_NATIVE=ON -DCMAKE_BUILD_TYPE=Release -DLLAMA_BUILD_TESTS=OFF 
    && cmake --build build --config Release -j$(nproc)**

Here are the errors I got:
...
common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
Flash Attention kernel: TILE
**MMQ kernel config: ITER_K=256, NWARPS=2 (GFX906 optimizations)
Memory access fault by GPU node-2 (Agent handle: 0x55a2d1feaea0) on address 0x7f7680f4d000. Reason: Page not present or supervisor privilege.
Failed to enable debug interface, debugger might be already attached.
GPU core dump failed
Kernel Name: _ZL17quantize_mmq_q8_1IL18mmq_q8_1_ds_layout0EEvPKfPKiPvlllllii
VGPU=0x55a2d23065e0 SWq=0x7f52a82f6000, HWq=0x7f519c200000, id=3**
/models/run_gpt-oss-20b.sh: line 1: 18798 Aborted                 (core dumped) ./llama-server --port 8000 --host 0.0.0.0 --model /models/ggml-org/gpt-oss-20b-GGUF/gpt-oss-20b-mxfp4.gguf -fa 1 --jinja --ctx-size 32768 --temp 1.0 --min-p 0.0 --top-k 0 --top-p 1.0 --n-gpu-layers 99 --main-gpu 0 --parallel 1 --reasoning-format auto --alias GPT-OSS-20B --chat-template-kwargs '{"reasoning_effort": "low"}'

I really appreciate the work you’ve done on this repo. I’m eager to try this implementation and will provide further debug info as I continue testing. Thank you!

### Relevant log output

```shell
...
[ 25%] Building HIP object ggml/src/ggml-hip/CMakeFiles/ggml-hip.dir/__/ggml-cuda/template-instances/fattn-tile-instance-dkq112-dv112.cu.o
In file included from /llama.cpp-gfx906/ggml/src/ggml-cuda/fattn.cu:11:
/llama.cpp-gfx906/ggml/src/ggml-cuda/gfx906/gfx906-fattn-q8.cuh:1069:9: warning: 'DECL_FATTN_TILE_CASE' macro redefined [-Wmacro-redefined]
 1069 | #define DECL_FATTN_TILE_CASE(DKQ, DV)                             \
      |         ^
/llama.cpp-gfx906/ggml/src/ggml-cuda/fattn-tile.cuh:1221:9: note: previous definition is here
 1221 | #define DECL_FATTN_TILE_CASE(DKQ, DV)                             \
      |         ^
/llama.cpp-gfx906/ggml/src/ggml-cuda/mmid.cu:28:24: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
   28 | static __global__ void mm_ids_helper(
      |                        ^
1 warning generated when compiling for gfx906.
1 warning generated when compiling for gfx906.
[ 25%] Building HIP object ggml/src/ggml-hip/CMakeFiles/ggml-hip.dir/__/ggml-cuda/template-instances/fattn-tile-instance-dkq128-dv128.cu.o
...
[ 35%] Building HIP object ggml/src/ggml-hip/CMakeFiles/ggml-hip.dir/__/ggml-cuda/template-instances/mmq-instance-q4_0.cu.o
In file included from /llama.cpp-gfx906/ggml/src/ggml-cuda/fattn.cu:11:
/llama.cpp-gfx906/ggml/src/ggml-cuda/gfx906/gfx906-fattn-q8.cuh:1069:9: warning: 'DECL_FATTN_TILE_CASE' macro redefined [-Wmacro-redefined]
 1069 | #define DECL_FATTN_TILE_CASE(DKQ, DV)                             \
      |         ^
/llama.cpp-gfx906/ggml/src/ggml-cuda/fattn-tile.cuh:1221:9: note: previous definition is here
 1221 | #define DECL_FATTN_TILE_CASE(DKQ, DV)                             \
      |         ^
[ 35%] Building HIP object ggml/src/ggml-hip/CMakeFiles/ggml-hip.dir/__/ggml-cuda/template-instances/mmq-instance-q4_1.cu.o
[ 36%] Building HIP object ggml/src/ggml-hip/CMakeFiles/ggml-hip.dir/__/ggml-cuda/template-instances/mmq-instance-q4_k.cu.o
1 warning generated when compiling for host.
...
[ 38%] Linking CXX shared library ../../bin/libggml-cpu.so
[ 38%] Built target ggml-cpu
In file included from /llama.cpp-gfx906/ggml/src/ggml-cuda/gfx906/template-instances/fattn-tile-q8-instance-dkq64-dv64.cu:3:
/llama.cpp-gfx906/ggml/src/ggml-cuda/gfx906/template-instances/../gfx906-fattn-q8.cuh:669:24: warning: failed to meet occupancy target given by 'amdgpu-waves-per-eu' in '_ZL18flash_attn_tile_q8ILi64ELi64ELi2ELi8ELb0EEvPKcS1_S1_S1_S1_PKiPfP15HIP_vector_typeIfLj2EEffffjfiiiiiiiiiiiiiliiliiiiil': desired occupancy was 2, final occupancy is 1 [-Wpass-failed]
  669 | static __global__ void flash_attn_tile_q8(
      |                        ^
/llama.cpp-gfx906/ggml/src/ggml-cuda/gfx906/template-instances/../gfx906-fattn-q8.cuh:669:24: warning: failed to meet occupancy target given by 'amdgpu-waves-per-eu' in '_ZL18flash_attn_tile_q8ILi64ELi64ELi4ELi4ELb0EEvPKcS1_S1_S1_S1_PKiPfP15HIP_vector_typeIfLj2EEffffjfiiiiiiiiiiiiiliiliiiiil': desired occupancy was 2, final occupancy is 1 [-Wpass-failed]
/llama.cpp-gfx906/ggml/src/ggml-cuda/gfx906/template-instances/../gfx906-fattn-q8.cuh:669:24: warning: failed to meet occupancy target given by 'amdgpu-waves-per-eu' in '_ZL18flash_attn_tile_q8ILi64ELi64ELi1ELi4ELb0EEvPKcS1_S1_S1_S1_PKiPfP15HIP_vector_typeIfLj2EEffffjfiiiiiiiiiiiiiliiliiiiil': desired occupancy was 3, final occupancy is 2 [-Wpass-failed]
/llama.cpp-gfx906/ggml/src/ggml-cuda/gfx906/template-instances/../gfx906-fattn-q8.cuh:669:24: warning: failed to meet occupancy target given by 'amdgpu-waves-per-eu' in '_ZL18flash_attn_tile_q8ILi64ELi64ELi8ELi2ELb0EEvPKcS1_S1_S1_S1_PKiPfP15HIP_vector_typeIfLj2EEffffjfiiiiiiiiiiiiiliiliiiiil': desired occupancy was 2, final occupancy is 1 [-Wpass-failed]
/llama.cpp-gfx906/ggml/src/ggml-cuda/gfx906/template-instances/../gfx906-fattn-q8.cuh:669:24: warning: failed to meet occupancy target given by 'amdgpu-waves-per-eu' in '_ZL18flash_attn_tile_q8ILi64ELi64ELi2ELi2ELb0EEvPKcS1_S1_S1_S1_PKiPfP15HIP_vector_typeIfLj2EEffffjfiiiiiiiiiiiiiliiliiiiil': desired occupancy was 3, final occupancy is 2 [-Wpass-failed]
/llama.cpp-gfx906/ggml/src/ggml-cuda/gfx906/template-instances/../gfx906-fattn-q8.cuh:669:24: warning: failed to meet occupancy target given by 'amdgpu-waves-per-eu' in '_ZL18flash_attn_tile_q8ILi64ELi64ELi1ELi2ELb0EEvPKcS1_S1_S1_S1_PKiPfP15HIP_vector_typeIfLj2EEffffjfiiiiiiiiiiiiiliiliiiiil': desired occupancy was 3, final occupancy is 2 [-Wpass-failed]
[ 38%] Linking CXX static library libcpp-httplib.a
[ 38%] Built target cpp-httplib
/llama.cpp-gfx906/ggml/src/ggml-cuda/gfx906/template-instances/../gfx906-fattn-q8.cuh:669:24: warning: failed to meet occupancy target given by 'amdgpu-waves-per-eu' in '_ZL18flash_attn_tile_q8ILi64ELi64ELi16ELi1ELb0EEvPKcS1_S1_S1_S1_PKiPfP15HIP_vector_typeIfLj2EEffffjfiiiiiiiiiiiiiliiliiiiil': desired occupancy was 2, final occupancy is 1 [-Wpass-failed]
/llama.cpp-gfx906/ggml/src/ggml-cuda/gfx906/template-instances/../gfx906-fattn-q8.cuh:669:24: warning: failed to meet occupancy target given by 'amdgpu-waves-per-eu' in '_ZL18flash_attn_tile_q8ILi64ELi64ELi4ELi1ELb0EEvPKcS1_S1_S1_S1_PKiPfP15HIP_vector_typeIfLj2EEffffjfiiiiiiiiiiiiiliiliiiiil': desired occupancy was 3, final occupancy is 1 [-Wpass-failed]
/llama.cpp-gfx906/ggml/src/ggml-cuda/gfx906/template-instances/../gfx906-fattn-q8.cuh:669:24: warning: failed to meet occupancy target given by 'amdgpu-waves-per-eu' in '_ZL18flash_attn_tile_q8ILi64ELi64ELi2ELi1ELb0EEvPKcS1_S1_S1_S1_PKiPfP15HIP_vector_typeIfLj2EEffffjfiiiiiiiiiiiiiliiliiiiil': desired occupancy was 3, final occupancy is 2 [-Wpass-failed]
9 warnings generated when compiling for gfx906.
In file included from /llama.cpp-gfx906/ggml/src/ggml-cuda/gfx906/template-instances/fattn-tile-q8-instance-dkq128-dv128.cu:3:
/llama.cpp-gfx906/ggml/src/ggml-cuda/gfx906/template-instances/../gfx906-fattn-q8.cuh:669:24: warning: failed to meet occupancy target given by 'amdgpu-waves-per-eu' in '_ZL18flash_attn_tile_q8ILi128ELi128ELi1ELi4ELb0EEvPKcS1_S1_S1_S1_PKiPfP15HIP_vector_typeIfLj2EEffffjfiiiiiiiiiiiiiliiliiiiil': desired occupancy was 2, final occupancy is 1 [-Wpass-failed]
  669 | static __global__ void flash_attn_tile_q8(
      |                        ^
/llama.cpp-gfx906/ggml/src/ggml-cuda/gfx906/template-instances/../gfx906-fattn-q8.cuh:669:24: warning: failed to meet occupancy target given by 'amdgpu-waves-per-eu' in '_ZL18flash_attn_tile_q8ILi128ELi128ELi2ELi2ELb0EEvPKcS1_S1_S1_S1_PKiPfP15HIP_vector_typeIfLj2EEffffjfiiiiiiiiiiiiiliiliiiiil': desired occupancy was 2, final occupancy is 1 [-Wpass-failed]
/llama.cpp-gfx906/ggml/src/ggml-cuda/gfx906/template-instances/../gfx906-fattn-q8.cuh:669:24: warning: failed to meet occupancy target given by 'amdgpu-waves-per-eu' in '_ZL18flash_attn_tile_q8ILi128ELi128ELi4ELi1ELb0EEvPKcS1_S1_S1_S1_PKiPfP15HIP_vector_typeIfLj2EEffffjfiiiiiiiiiiiiiliiliiiiil': desired occupancy was 2, final occupancy is 1 [-Wpass-failed]
/llama.cpp-gfx906/ggml/src/ggml-cuda/gfx906/template-instances/../gfx906-fattn-q8.cuh:669:24: warning: failed to meet occupancy target given by 'amdgpu-waves-per-eu' in '_ZL18flash_attn_tile_q8ILi128ELi128ELi1ELi4ELb1EEvPKcS1_S1_S1_S1_PKiPfP15HIP_vector_typeIfLj2EEffffjfiiiiiiiiiiiiiliiliiiiil': desired occupancy was 2, final occupancy is 1 [-Wpass-failed]
/llama.cpp-gfx906/ggml/src/ggml-cuda/gfx906/template-instances/../gfx906-fattn-q8.cuh:669:24: warning: failed to meet occupancy target given by 'amdgpu-waves-per-eu' in '_ZL18flash_attn_tile_q8ILi128ELi128ELi2ELi2ELb1EEvPKcS1_S1_S1_S1_PKiPfP15HIP_vector_typeIfLj2EEffffjfiiiiiiiiiiiiiliiliiiiil': desired occupancy was 2, final occupancy is 1 [-Wpass-failed]
/llama.cpp-gfx906/ggml/src/ggml-cuda/gfx906/template-instances/../gfx906-fattn-q8.cuh:669:24: warning: failed to meet occupancy target given by 'amdgpu-waves-per-eu' in '_ZL18flash_attn_tile_q8ILi128ELi128ELi4ELi1ELb1EEvPKcS1_S1_S1_S1_PKiPfP15HIP_vector_typeIfLj2EEffffjfiiiiiiiiiiiiiliiliiiiil': desired occupancy was 2, final occupancy is 1 [-Wpass-failed]
6 warnings generated when compiling for gfx906.
[ 38%] Linking HIP shared library ../../../bin/libggml-hip.so
[ 38%] Built target ggml-hip
[ 39%] Building CXX object ggml/src/CMakeFiles/ggml.dir/ggml-backend-reg.cpp.o
[ 39%] Linking CXX shared library ../../bin/libggml.so
[ 39%] Built target ggml
...
```

**Comment by Kotali-2019** [comment]
Thank you for the quick response.
I confirm that Qwen3-4B-Instruct-2507-Q4_K_M.gguf works. I’ll try your suggestion soon with a fresh OS and ROCm installation.
I suspect mxfp4 may have caused the problem.

**Comment by iacopPBK** [comment]
Sorry may have been wrong: i experienced again the stuck at loading issue using MXFP4 gguf. The F16 version should work well. This is strange because there is other people who say it works 😆.

Im having the exact same issue (quantize_q8...): problem is mm_ids_helper kernel that messes up data because is doing reductions with 32 threads on 64 threads wavefronts. I don't know why it works for some users, maybe their compilers are doing the job correctly...

I'm testing the fix and it works for me, i will test this on other machines and release it once ready!

By the way: normal llamacpp works well right?

Thank you !!

**Comment by Kotali-2019** [comment]
Yeah, normal llamacpp works well.
Thank you for taking the time to look into my issue!

**Comment by Kotali-2019** [comment]
Hi,
I recently tried recompiling the binary from this fork. I’m still encountering the same errors with the MXFP4 GGUF file (llama-server). However, the Qwen3-Next model works fine with this build.
Additionally, I noticed that llama-bench runs successfully with the MXFP4 GGUF format and performs faster than the standard llama.cpp.
I’d like to share my build command and some related details:

> cmake -S . -B build-rocm906-host -DGGML_HIP=ON -DAMDGPU_TARGETS=gfx906 \
-DGGML_RPC=ON -DLLAMA_CURL=OFF \
-DCMAKE_BUILD_TYPE=Release -DLLAMA_BUILD_TESTS=OFF
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_BUILD_TYPE=Release
-- Found Git: /usr/bin/git (found version "2.39.5")
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Warning: ccache not found - consider installing it for faster compilation or disable this warning with GGML_CCACHE=OFF
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- GGML_SYSTEM_ARCH: x86
-- Including CPU backend
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- x86 detected
-- Adding CPU backend variant ggml-cpu: -march=native
-- The HIP compiler identification is Clang 19.0.0
-- Detecting HIP compiler ABI info
-- Detecting HIP compiler ABI info - done
-- Check for working HIP compiler: /opt/rocm-6.4.4/lib/llvm/bin/clang++ - skipped
-- Detecting HIP compile features
-- Detecting HIP compile features - done
-- HIP and hipBLAS found
-- GFX906 .cu files found: /root/llama.cpp-gfx906/ggml/src/ggml-hip/../ggml-cuda/gfx906/gfx906-fattn-q8.cu
-- GFX906 template instances found: /root/llama.cpp-gfx906/ggml/src/ggml-hip/../ggml-cuda/gfx906/template-instances/fattn-tile-q8-instance-dkq112-dv112.cu;/root/llama.cpp-gfx906/ggml/src/ggml-hip/../ggml-cuda/gfx906/template-instances/fattn-tile-q8-instance-dkq128-dv128.cu;/root/llama.cpp-gfx906/ggml/src/ggml-hip/../ggml-cuda/gfx906/template-instances/fattn-tile-q8-instance-dkq256-dv256.cu;/root/llama.cpp-gfx906/ggml/src/ggml-hip/../ggml-cuda/gfx906/template-instances/fattn-tile-q8-instance-dkq40-dv40.cu;/root/llama.cpp-gfx906/ggml/src/ggml-hip/../ggml-cuda/gfx906/template-instances/fattn-tile-q8-instance-dkq576-dv512.cu;/root/llama.cpp-gfx906/ggml/src/ggml-hip/../ggml-cuda/gfx906/template-instances/fattn-tile-q8-instance-dkq64-dv64.cu;/root/llama.cpp-gfx906/ggml/src/ggml-hip/../ggml-cuda/gfx906/template-instances/fattn-tile-q8-instance-dkq80-dv80.cu;/root/llama.cpp-gfx906/ggml/src/ggml-hip/../ggml-cuda/gfx906/template-instances/fattn-tile-q8-instance-dkq96-dv96.cu
-- Including HIP backend
-- Using RPC backend
-- Including RPC backend
-- ggml version: 0.9.4
-- ggml commit:  4cf0b39b
-- Configuring done
-- Generating done
-- Build files have been written to: /root/llama.cpp-gfx906/build-rocm906-host

**Comment by iacopPBK** [comment]
Hi, im updating the repo by this week with fixes for the mxfp4 issue (and many more). I think the qwen3-next only runs on cpu with this version. I may be wrong. 

Sorry for the update delay im a bit busy in these days! 

The update will be 2512 version so easy to recognize
